### ISSUE TITLE
Error in monokai.lua

### ISSUE THREAD

**Issue by ad1tyawagh** [tanvirtin/monokai.nvim#1]
Any idea what the issue is? I can't understand what is wrong.

## Error

NeoVim throws this error at startup.

```
Error detected while processing C:\Users\adiwa\.vim\plugged\nvim-monokai\colors\monokai.vim:
line    1:
E5105: Error while calling lua chunk: C:\Users\adiwa\.vim\plugged\nvim-monokai\lua\monokai.lua:521: attempt to index field 'fn' (a nil value)
```

The exact line that is showing up in the error:

https://github.com/tanvirtin/monokai.nvim/blob/3b690bdc19ae0cf84bd62965202f898c3dc00f8e/lua/monokai.lua#L521

## My init.vim file
```vim
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'itchyny/lightline.vim'
Plug 'tanvirtin/nvim-monokai'
call plug#end()

" let g:gruvbox_contrast_dark = 'hard'
" let g:lightline = {
" \ 'colorscheme': 'gruvbox',
" \ 'separator': { 'left': '', 'right': '' },
" \ 'subseparator': { 'left': '', 'right': '' }
" \ }

syntax on
set number
colorscheme monokai
set termguicolors
set noshowmode
```

**Comment by tanvirtin** [comment]
Hey there, what version of Neovim are you running the plugin on?

**Comment by ad1tyawagh** [comment]
I'm using v0.4.4 on Windows 10. 
Installed it using **scoop**.

**Comment by tanvirtin** [comment]
The plugin references code written for Neovim 0.5, such as vim.fn.exists, I have updated the docs with Neovim 0.5 as prerequisites for the project upgrading to the [nightly build](https://github.com/neovim/neovim/releases) should solve the issue.

**Comment by ad1tyawagh** [comment]
Great! That fixed my issue. However, I am having issues with the background of the Monokai.

Have a look.

![bg-issue](https://user-images.githubusercontent.com/25822972/112243480-a27a8c00-8c73-11eb-96c0-bd12a4d60e2f.png)

Any idea why I am getting a different background?

**Comment by ad1tyawagh** [comment]
Found the issue.  I didn't configure `neovim-nightly`! Also, I had enabled OneDark theme for CMD, which is the reason I am getting that background. Sorry!
