### ISSUE TITLE
Feature request: Add italic support

### ISSUE THREAD

**Issue by mrkz** [tanvirtin/monokai.nvim#10]
Please add support for Italics, for reference, I got this [hello_world.rs](https://doc.rust-lang.org/rust-by-example/hello.html) screenshots where `tomasr/molokai` [theme](https://github.com/tomasr/molokai) has support for italics (e.g: rust uses them in *`macro!`* invocations).

Attaching screenshots to see a diff on the *`println!`* call difference, see line 13 as an example.  (I really like this theme btw, thanks!)

**`tomasr/molokai` with *italic* support**:
![molokai](https://user-images.githubusercontent.com/978752/131413428-b28d45c3-569a-40e4-95cb-3503dade28fb.png)
**`tanvirtin/monokai.nvim`**
![monokai](https://user-images.githubusercontent.com/978752/131413436-46540b9b-9d33-45c4-b1d9-1b46dfc9dae1.png)

Thanks again for your time and your effort on the project!

**Comment by tanvirtin** [comment]
Hi there, glad you are enjoying the colorscheme! I have updated support for italics on some keywords such as:
- Macro function calls
- Function declaration keyword
- Comments

If things look good to you feel free to close this issue, thank you!
