### ISSUE TITLE
How do I make the background transparent

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [tanvirtin/monokai.nvim#13]
I have made the background transparent in the terminal itself:
![Screenshot from 2021-10-29 18-58-51-censored](https://user-images.githubusercontent.com/68545280/139481671-0981b7a2-6057-4f75-b8c5-b88674835feb.png)

And when I open neovim with no theme set (commented out), the background stays transparent:
![Screenshot from 2021-10-29 18-59-19](https://user-images.githubusercontent.com/68545280/139481731-f8125a4d-7c43-4bcc-a48e-f042d63c039f.png)

But when I apply the theme, it is opaque: 
![Screenshot from 2021-10-29 18-59-35](https://user-images.githubusercontent.com/68545280/139481773-07bad1d5-845f-4f67-82f9-66760e9cb269.png)

I want it to be about 95% opaque, rather than 100%, so how do I configure that?.

**Comment by CSpencerND** [comment]
Try this?
`:hi Normal ctermbg=none guibg=none`

**Comment by DragonEggBedrockBreaking** [comment]
> Try this? `:hi Normal ctermbg=none guibg=none`

Thanks, that worked. For anyone wondering how to put that in the `init.lua` (where simply putting that code in `vim.cmd([[]])` doesn't work for some reason), here is the code I eventually found and edited:
```lua
vim.cmd([[
augroup TransparentColours
autocmd!
autocmd ColorScheme * highlight normal ctermbg=NONE guiBG=NONE
augroup end
]])
```

**Comment by GiovanePS** [comment]
In LazyVim i do that to set transparency:
![image](https://github.com/tanvirtin/monokai.nvim/assets/57882319/e843f71d-df76-4db0-8fbb-9072c22b623a)

**Comment by carter2099** [comment]
Hi @GiovanePS for future reference pls post code to make it easy to copy paste instead of a screenshot. Appreciate the tip though and your colors look great!

**Comment by GiovanePS** [comment]
@carter2099 You're absolutely right! Forgive me for this. Did you get the code?

If not, here it is. Sorry, again :)

```
return {
	{
		"tanvirtin/monokai.nvim",
		enabled = true,
		lazy = true,
		priority = 1000,
		config = function()
			require("monokai").setup({
				palette = require("monokai").soda,
			})

			vim.cmd([[colorscheme monokai]])
			vim.defer_fn(function()
				vim.cmd([[
					hi Normal guibg=none ctermbg=none
					hi LineNr guibg=none guifg=#999999 ctermbg=none
					hi SignColumn guibg=none ctermbg=none
					hi CursorLineNr guibg=none ctermbg=none
					hi Visual guibg=#5F5A60
					hi MatchParen cterm=bold ctermbg=none ctermfg=none guibg=#97e023 guifg=#333842
					hi MsgArea guibg=#222426
				]])
			end, 600)
		end,
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "monokai",
		},
	},
}
```
