### ISSUE TITLE
tab list char not legible

### ISSUE THREAD

**Issue by kaihendry** [tanvirtin/monokai.nvim#14]
![image](https://user-images.githubusercontent.com/765871/141236145-96adb12c-57be-44ce-bcb5-9c6304f86230.png)

    set list listchars=nbsp:¬,tab:»·,trail:·,extends:>

I can hardly see the white space tab character when using monokai

**Comment by raiyuza** [comment]
Good thing is customisable, you could fork your own version. This is the authors vision how it should represent. Also it seems you are using bg=dark instead of light ;)

**Comment by gtklocker** [comment]
I agree that listchars are not legible, @tanvirtin how do you feel about changing Whitespace from base3 to base6 or 7?

**Comment by tanvirtin** [comment]
@gtklocker I personally like base3, but if multiple plugin users have an issue with it then absolutely, open to all PRs.
