### ISSUE TITLE
jsx tags not highlighting properly

### ISSUE THREAD

**Issue by wilkinson4** [tanvirtin/monokai.nvim#15]
Hello! I am noticing an issue with jsx syntax highlighting not picking up the jsx tags. Please see below:
<img width="1039" alt="Screen Shot 2021-12-10 at 4 37 35 PM" src="https://user-images.githubusercontent.com/40211746/145650107-86fc89e4-2cfd-424e-a3df-d5faf7a05903.png">
I am running into the same issue in tsx files as well. I am using Treesitter, and vim-polygot all updated to the latest versions.
Neovim: 0.5.1

**Comment by wilkinson4** [comment]
I recently fixed it via my config with the following code:
```lua
local monokai = require('monokai')
local palette = monokai.pro

vim.highlight.create('TSParameter', {guifg=palette.orange})
```
![Screen Shot 2021-12-13 at 4 09 50 PM](https://user-images.githubusercontent.com/40211746/145897044-c7f90868-ded0-4802-9d7a-2eddbe774911.png)

**Comment by zxxia** [comment]
Thanks for the code snippet! It fixes the constructor highlighting in python as well.

**Comment by tanvirtin** [comment]
Hey thanks for the issue, I apologize for the late reply.

This looks like a great addition. If you want feel free to open a pull request with the update, all you would need to do is add a line [here](https://github.com/tanvirtin/monokai.nvim/blob/master/lua/monokai.lua#L403) with the new highlight.

**Comment by wilkinson4** [comment]
> Hey thanks for the issue, I apologize for the late reply.
> 
> This looks like a great addition. If you want feel free to open a pull request with the update, all you would need to do is add a line [here](https://github.com/tanvirtin/monokai.nvim/blob/master/lua/monokai.lua#L403) with the new highlight.

Done!
https://github.com/tanvirtin/monokai.nvim/pull/20
