### ISSUE TITLE
DiffChange and DiffDelete colors are swapped

### ISSUE THREAD

**Issue by Rahix** [tanvirtin/monokai.nvim#5]
Hi,

it appears that the diff highlights are swapped:

https://github.com/tanvirtin/monokai.nvim/blob/217ec46c02dadbe1f392725841b84653a63b3b33/lua/monokai.lua#L229-L236

Is this intentional or just an oversight?

**Comment by tanvirtin** [comment]
@Rahix, Thanks for taking the time to point this issue out. It's a mistake on my part.

I have issued a fix for it, take care.

**Comment by Rahix** [comment]
Thanks for the quick fix!  Loving the colorscheme, by the way :)
