### ISSUE TITLE
Background Not Highlighting

### ISSUE THREAD

**Issue by jpe90** [tanvirtin/monokai.nvim#7]
Hello,

My background seems not to be colored with this plugin. It seems like the commit below removed background highlighting when the colors were changed up, but I can see there's been more activity since then and nobody has raised an issue (maybe you all use a monokai color scheme in your terminal so you wouldn't notice?) ... sorry if I've made some mistake! 

https://github.com/tanvirtin/monokai.nvim/blob/27aa08180938cab0e10add0974a530e7388dff5e/lua/monokai.lua#L46

**Comment by nicolas-yangli** [comment]
I encountered the same problem.
